LOCAL_PATH := $(call my-dir)

#include $(CLEAR_VARS)
#LOCAL_CFLAGS := -g -DDEBUG 
#LOCAL_MODULE := DMService
#LOCAL_SRC_FILES := libDMService.so
#include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_CFLAGS := -g -DDEBUG
LOCAL_C_INCLUDES := $(LOCAL_PATH)
#LOCAL_C_INCLUDES := InitDaemon.h
LOCAL_MODULE := DMApp
LOCAL_STATIC_LIBRARIES := DMService
LOCAL_LDLIBS := -llog 
LOCAL_SRC_FILES := Test.c
LIB_PATH := $(LOCAL_PATH)/../libs
#LOCAL_LDLIBS += -L $(LIB_PATH)
include $(BUILD_SHARED_LIBRARY)
